---
title: "Interpreting wind damage - How management impacts standing timber at risk of wind felling"
subtitle: "Supplementary Material"
author: "Mária Potterf, Kyle Eyvindson, Clemens Blattert, Daniel Burgas, Mikko Mönkkönen"


date: "March 10, 2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list = ls())

# Read libraries ----
require("knitr")

knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = "C:/MyTemp/myGitLab/windDamage/output/even_flow")

```


```{r read-libs, eval = T, echo = F, warning = F, message = F, include = F }


library(data.table)
library(dplyr)
library(raster)
library(ggplot2)
library(sf)
library(stringr)
library(gridExtra)
library(tidyr)
library(ggpubr)
library(broom)
#library(RColorBrewer)
```

```{r set-theme, eval = T, echo = F, warning = F, message = F, include = F }

# Set themes ----
theme_set(theme_classic())
theme_update(panel.grid.major = element_line(colour = "grey95",
                                             size = 0.1,
                                             linetype = 2),
             strip.background = element_rect(color="grey95", 
                                             fill="grey95",
                                             size=0.1, 
                                             linetype="solid"))

# Define own palette, color blind
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


```


```{r read-data, eval = T, echo = F, warning = F, message = F, include = F }

# Set wd ------------------------------------------------------------------
#require("knitr")
#opts_knit$set(root.dir = "C:/MyTemp/myGitLab/windDamage/output/even_flow")
#getwd()
#setwd("C:/MyTemp/myGitLab/windDamage/output/even_flow")

# Read input data ----------------------------------------------------

# includes optimal scenario, raster data, windRisk
df <- fread("C:/MyTemp/myGitLab/windDamage/output/even_flow/finalFoPlotting.csv")

source("C:/MyTemp/myGitLab/windDamage/myFunctions.R")

```
```{r hist-Suvanto-values, eval = T, echo = F, warning = F, message = F, include = T, fig.width = 5, fig.height = 2.7, fig.cap = "\\label{fig:fig_meanRisk_time_NPI} Wind damage probabilities (%) for forest stands located in the watershed (number 14.358) from original Suvanto's raster and from our simulated data in 2016. "}

# Read extracted  raster Suvanto data to get histogram
# subset my data for 2016
# merge data in one dataframe to create a plot

library(raster)

suvanto_risk <- raster("C:/MyTemp/mapWindRisk/tuuliSuvanto/extract_pred_N4.tif")

suvanto_df <- as.data.frame(suvanto_risk, na.rm = T)
suvanto_df$cat = "Suvanto"  # add new column
names(suvanto_df) <- c("windRisk", "cat")


# Subset simulated data for 2016
df_risk <- df %>% 
  filter(year == 2016) %>% 
  dplyr::select(windRisk) %>% 
  mutate(cat = "SIMO")


#Merge data together
df_comp <- rbind(suvanto_df,
                 df_risk  )

# make a plot
ggplot(df_comp, aes(x = cat,
                    y = windRisk,
                    fill = cat,
                    group = cat)) + 
  geom_boxplot(alpha = .5, 
               outlier.shape = NA) + 
  stat_summary(geom = "point", color = "red") + # mean +- se 
  ylab("Wind damage probability (%)") + 
  labs(fill = "Data source") +
  xlab("") + 
  ylim(0, 0.10)

```



```{r plot-total-V, eval = T, echo = F, warning = F, message = F, include = T, fig.width = 7, fig.height = 3, fig.cap = "\\label{fig:plot-total-V} Mean total stand timber volume (m3/ha) for landscapes under RF, CCF and ALL scenarios over harvest intensity gradient (NPI, net present income, left column) and over time (right column) for actively managed stands and set asides."}



#### Total volume at risk ---------------
p.mean.V.line.npi <-
  df %>% 
  group_by(scenSimpl2, 
           NPI, 
           Management) %>% 
  summarize(my_y = mean(V, na.rm =T ))  %>% # there are NA if V and V_strat_max = 0
  ggplot(aes(y = my_y, 
             x = NPI, 
             shape = scenSimpl2,     
             color = scenSimpl2,     
             linetype = scenSimpl2,  
             group = scenSimpl2,     
             fill = scenSimpl2 )) +  
  ylim(0,350) +
  xlab("Net present income\n(k€/ha)") + #
  ylab("Total stand volume\n(mean, m^3)") +
  plot_line_details()



p.mean.V.line.time <-
  df %>% 
  group_by(scenSimpl2, 
           year, 
           Management) %>% 
  summarize(my_y = mean(V, na.rm =T ))  %>% # there are NA if V and V_strat_max = 0
  ggplot(aes(y = my_y, 
             x = year, 
             shape = scenSimpl2,     
             color = scenSimpl2,     
             linetype = scenSimpl2,  
             group = scenSimpl2,     
             fill = scenSimpl2 )) +  
  ylim(0,350) +
  xlab("Time\n") + #
  ylab("Total stand volume\n(mean, m^3)") +
  plot_line_details()


# Plot by managed/unmanaged stands 
#windows(width = 7, height=6)
ggarrange(p.mean.V.line.npi, 
          p.mean.V.line.time,
          ncol = 2, nrow = 1,
          widths = c(1, 1),
          common.legend = TRUE,
          align = c("hv"),
          legend="bottom",
          labels= "AUTO",
          hjust = -5,
          vjust = 3,
          font.label = list(size = 10, 
                            face = "bold", color ="black"))



```



```{r plot-dynamic-vars, eval = T, echo = F, warning = F, message = F, include = T, fig.width = 7, fig.height = 9.5, fig.cap = "\\label{fig:plot-dynamic-vars} FINISH THIS ONE!!!s."}

# Plot explanatory variables # ---------------------------------------------

# Tree species
# Tree height
# Time since thinning
# open-neighbour
## Tree species -------------------------

# Spruce is the most vulnerable: frequency of spruce

# Calculate the mean # of spruces!!
# over time and npi

# Calculate the mean # of spruces!! Why mean???
# How many stand I have for each simple scen vs NPI?
# what I want to show? how does the share of teh spruce changes over 
# harvest and time gradient??

# different number of stands by combination
# ranges from 29400 to 29280 - caulculate the % from the 29400 stands
tot.stand.n = 1470*20


# Spruce rate: Make plots for npi and time----------------------------

p.spruce.ratio.npi <-
  df %>% 
  group_by(scenSimpl2, 
           NPI, 
           Management) %>% 
  filter(species == "spruce") %>% 
  tally() %>%
  mutate(spruce_prop = n/tot.stand.n*100)  %>%  # get the proportion of spruce from all stands over 20 years 
  ggplot(aes(y = spruce_prop, 
             x = NPI, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  xlab("NPI (k€/ha)") + #
  ylab("Spruce proportion\n(%)") +
  ylim(0,50) +
  plot_line_details()

# to calulate how many landscapes I have over time:
p.spruce.ratio.time <-
  df %>% 
  group_by(scenSimpl2, 
           year, 
           Management) %>% #, species
  filter(species == "spruce") %>% 
  tally() %>%
  mutate(spruce_prop = n/tot.stand.n*100)  %>%  # get the proportion of spruce from all stands over 20 years 
  ggplot(aes(y = spruce_prop, 
             x = year, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  ylim(0,50) +
  xlab("Time") + #
  ylab("Spruce proportion\n(%)") +
  plot_line_details()
  
 

## H Dom ---------------------
p.mean.H_dom.npi <-
  df %>% 
  group_by(scenSimpl2, 
           NPI, 
           Management) %>% 
  #summarize(s_area = sum(area)) %>% 
  summarize(my_y = weighted.mean(H_dom,  area, na.rm = T))  %>% 
 # summarize(my_y = mean(H_dom))  %>%
  ggplot(aes(y = my_y, 
             x = NPI, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  ylim(0,300) +
  ggtitle("") +
  xlab("NPI (k€/ha)") + #
  ylab("Tree height\n(w.mean, cm)") +
  plot_line_details()



p.mean.H_dom.time <-
  df %>% 
  group_by(scenSimpl2, 
           year, 
           Management) %>% 
  #summarize(my_y = mean(H_dom ))  %>%
  summarize(my_y = weighted.mean(H_dom,  area, na.rm = T))  %>% 
  ggplot(aes(y = my_y, 
             x = year, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  ylim(0,300) +
  ggtitle("") +
  xlab("Time ") + #
  ylab("Tree height\n(w. mean, cm)") +
  plot_line_details()



## Time since thinning ------------------------
# get the difference by landscape???
# replace NA by 0?
# get mean landscape differences by NPI, by time
# how to calculate the time since thinning? for NPi, for time??
# calculate weighted mean??
# get the sum of area and then calculate? yes, seems working and has the same results are using n


p.mean.thin.npi <-
  df %>% 
  group_by(scenSimpl2, 
           NPI, 
           Management,
           difference) %>% 
  summarize(s_area = sum(area)) %>% 
  summarize(my_y = weighted.mean(difference,  s_area, na.rm = T))  %>% 
 # tally() %>%
 # summarize(my_y = weighted.mean(difference, n, na.rm = T)) %>% 
  ggplot(aes(y = my_y, 
             x = NPI, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  ylim(0,30) +
  xlab("NPI (k€/ha)") + #
  ylab("Years since thinning\n(weigh. mean)") +
  plot_line_details()


# Mean thinning over time
p.mean.thin.time <-
  df %>% 
  group_by(scenSimpl2, 
           year, 
           Management,
           difference) %>% 
  summarize(s_area = sum(area)) %>% 
  summarize(my_y = weighted.mean(difference,  s_area, na.rm = T))  %>% 
  ggplot(aes(y = my_y, 
             x = year, 
             shape = scenSimpl2,
             color = scenSimpl2,
             linetype = scenSimpl2,
             group = scenSimpl2,
             fill = scenSimpl2)) +
  ylim(0,30) +
  xlab("Time ") + #
  ylab("Years since thinning\n(weigh. mean)") +
  plot_line_details()



p.mean.H_diff.line.npi <-
  df %>% 
  group_by(scenSimpl2, 
           NPI, 
           Management) %>% 
  #summarize(my_y = mean(mean_H_diff, na.rm =T ))  %>% # there are NA if V and V_strat_max = 0
  summarize(my_y = weighted.mean(mean_H_diff,  area, na.rm = T))  %>% 
  ggplot(aes(y = my_y, 
             x = NPI, 
             shape = scenSimpl2,     
             color = scenSimpl2,     
             linetype = scenSimpl2,  
             group = scenSimpl2,     
             fill = scenSimpl2 )) +  
  ylim(0,10) +
  xlab("NPI (k€/ha)") + #
  ylab("Height difference\nneighbors (mean, m)") +
  plot_line_details()



p.mean.H_diff.line.time <-
  df %>% 
  group_by(scenSimpl2, 
           year, 
           Management) %>% 
  #summarize(my_y = mean(mean_H_diff, na.rm =T ))  %>% 
  summarize(my_y = weighted.mean(mean_H_diff,  area, na.rm = T))  %>% 
  ggplot(aes(y = my_y, 
             x = year, 
             shape = scenSimpl2,     
             color = scenSimpl2,     
             linetype = scenSimpl2,  
             group = scenSimpl2,     
             fill = scenSimpl2 )) +  
  ylim(0,10) +
  xlab("Time") + #
  ylab("Height difference\nneighbors(mean, m)") +
  plot_line_details()

### Plot all predictors together --------------------------------------------

ggarrange(p.spruce.ratio.npi, p.spruce.ratio.time,
          p.mean.H_dom.npi,   p.mean.H_dom.time,
          p.mean.thin.npi,    p.mean.thin.time,
         # p.mean.open.edge.npi, p.mean.open.edge.time,
          p.mean.H_diff.line.npi, p.mean.H_diff.line.time, 
          ncol = 2, nrow = 4,
          #widths = c(1, 1),
          common.legend = TRUE,
          align = c("hv"),
          legend="bottom",
          labels= "AUTO",
          hjust = -5,
          vjust = 3,
          font.label = list(size = 10, 
                            face = "bold", color ="black"))


```


```{r  plot-SA-chars, eval = T, echo = F, warning = F, message = F, include = T, fig.width = 7, fig.height = 2.7, fig.cap = "\\label{fig:fig_meanRisk_time_NPI} FINISH THIS ONE !!!"}
# plot V, tree height, age

df_sub <- df %>% 
  filter(year == 2016 & Management == "Set Aside") %>% 
  filter(scenNumb == 1 | scenNumb == 20 ) %>%
  mutate(fc_scenNumb = factor(scenNumb, 
                              labels = c('Min', 'Max')))  # %>%
 # mutate(fc_scenNumb = factor(fc_scenNumb, 
   #                           levels = rev(levels(fc_scenNumb))))
  


# Make plots
p.1<-df_sub %>% 
  ggplot(aes(y = H_dom,
             x = fc_scenNumb,
             group = fc_scenNumb,
             fill = fc_scenNumb)) +
 geom_boxplot(alpha = .5, 
               outlier.shape = NA) + 
  stat_summary(fun.data=mean_sdl, geom="point", color="red")+
  facet_grid(.~Management) +
  ylab("Tree height (cm)") + 
  xlab("NPI (k€/ha)")

p.2<-df_sub %>% 
 # mutate(scenNumb = factor(scenNumb)) %>% 
  ggplot(aes(y = V_strat_max,
             x = fc_scenNumb,
             group = fc_scenNumb,
             fill = fc_scenNumb)) +
 geom_boxplot(alpha = .5, 
               outlier.shape = NA              ) + 
  stat_summary(fun.data=mean_sdl, geom="point", color="red")+
  facet_grid(.~Management) +
  ylab("Top stratum volume (m3/ha)") +
  xlab("NPI (k€/ha)")


ggarrange(p.1, p.2, 
          ncol = 2, nrow = 1,
          widths = c(1, 1),
          common.legend = FALSE,
          align = c("hv"),
          legend="bottom",
          labels= "AUTO",
          hjust = -5,
          vjust = 3,
          font.label = list(size = 10, 
                            face = "bold", color ="black"))


```